# 13_Keras 시작하기② Functional API
Linear Regression과 Logistic Regression을 Keras로 구현해보기

#### 실습목표<br>
무작정 따라하며 keras의 모델링 구조를 받아들인다.



## 1. Quick Linear Regression!

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * 2 -1 
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 1. 모델 선언하기
# ①세션 비우기 : 기계적으로 수행하자.
keras.backend.clear_session()

# ② 모델 정의
# 레이어들을 사슬로 연결하 듯이 연결! 모든 레이어 다 선언하고, 모든 레이어 연결까지 써줘야 한다.
input_layer = keras.layers.Input(shape=(1,))  #Input layer
output_layer = keras.layers.Dense(1)(input_layer)  # input layer에 out으로 연결

# ③ 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# ⑤ 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 2. 학습시키기
model.fit(x, y, epochs=10, verbose=1)


Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 1565.6689
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 1564.7224
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 1563.7764
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 1562.8307
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 1561.8854
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 1560.9402
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 1559.9954
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 1559.0508
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 1558.1067
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 1557.1627


In [ ]:
# 3. 예측하기

print(y[15:])
print(model.predict(x[15:]))

[29 31 33 35 37]
[[-24.397446]
 [-26.024609]
 [-27.651772]
 [-29.278934]
 [-30.906097]]


## 2. 실습 : 무작정 따라하기
일단 코드 작성할 수 있는 수준에 도달해 봅시다.  
위 내용을 그대로 배껴서 작성해 봅시다.   
**ctrl+c, +v 안됩니다!**

In [6]:
# 패키지 로딩부터
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np



In [7]:
x = np.array(range(0,20)) 
y = x * (-3) + 10 
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [11]:
# 1. 모델 선언하기
# ①세션 비우기 : 기계적으로 수행하자.
keras.backend.clear_session()

# ② 모델 정의
# 레이어들을 사슬로 연결하 듯이 연결! 모든 레이어 다 선언하고, 모든 레이어 연결까지 써줘야 한다.
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

# ③ 모델의 시작과 끝을 지정
model = keras.models.Model(inputs = il, outputs = ol)

# ⑤ 컴파일
model.compile(loss = 'mse', optimizer = 'adam')

In [12]:
# 2. 학습시키기
model.fit(x,y,epochs=10, verbose=1)



Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 185.6396
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 185.3436
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 185.0479
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 184.7525
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 184.4574
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 184.1626
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 183.8681
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 183.5739
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 183.2800
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 182.9865


In [13]:
# 3. 예측하기
print(y[15:])
print(model.predict(x[15:]))


[-35 -38 -41 -44 -47]
[[-16.616789]
 [-17.72391 ]
 [-18.83103 ]
 [-19.938148]
 [-21.045267]]


## 3. Quick Logistic Regression!

In [14]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [15]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [16]:
# 1. 모델 선언하기
# ①세션 비우기 : 기계적으로 수행하자.
keras.backend.clear_session()

# ② 모델 정의
# 레이어들을 사슬로 연결하 듯이 연결! 모든 레이어 다 선언하고, 모든 레이어 연결까지 써줘야 한다.
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# ③ 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# ⑤ 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam')

In [17]:
# 2. 학습시키기
model.fit(x[:15], y[:15], epochs=10, verbose=1)


Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 0.7022
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 0.7013
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 0.7005
Epoch 4/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6996
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6988
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6980
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6972
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6964
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6956
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6948


In [18]:
# 3. 예측하기
print(y[15:])
print(model.predict(x[15:]))

[1 1 1 1 1]
[[0.48007533]
 [0.47891548]
 [0.47775584]
 [0.47659642]
 [0.47543728]]


## 4. 실습 : 무작정 따라하기

In [28]:
# 패키지 로딩부터
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np



In [29]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [30]:
# 1. 모델 선언하기
# ①세션 비우기 : 기계적으로 수행하자.
keras.backend.clear_session()

# ② 모델 정의
# 레이어들을 사슬로 연결하 듯이 연결! 모든 레이어 다 선언하고, 모든 레이어 연결까지 써줘야 한다.
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

# ③ 모델의 시작과 끝을 지정
model = keras.models.Model(inputs = il, outputs=ol)

# ⑤ 컴파일
model.compile(loss='binary_crossentropy', optimizer = 'adam')

In [31]:
# 2. 학습시키기
model.fit(x[15:], y[15:], epochs = 10)


Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 32.9320
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 32.9076
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 32.8832
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 32.8587
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 32.8343
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 32.8099
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 32.7855
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 32.7611
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 32.7367
Epoch 10/10
1/1 [==============================] - 0s 1ms/step - loss: 32.7123


In [32]:
# 3. 예측하기
print(y[15:])
print(model.predict(x[15:]))


[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[9.5308372e-10]
 [2.3847893e-10]
 [5.9671781e-11]
 [1.4930968e-11]
 [3.7360080e-12]
 [9.3481733e-13]
 [2.3390835e-13]
 [5.8528255e-14]
 [1.4644837e-14]
 [3.6643984e-15]
 [9.1689940e-16]
 [2.2942496e-16]
 [5.7406308e-17]
 [1.4364160e-17]
 [3.5941750e-18]
 [8.9932824e-19]
 [2.2502833e-19]
 [5.6306197e-20]
 [1.4088837e-20]
 [3.5252842e-21]
 [8.8209048e-22]
 [2.2071513e-22]
 [5.5227161e-23]
 [1.3818844e-23]
 [3.4577264e-24]]
